config/routes.rb
Rails.application.routes.draw do

root 'pages#about'

resources :cases do
  collection do
    get 'by-subject' => 'cases#index_by_keyword', as: :by_keyword
  end
end

get 'admin/case' => 'admin#case_dashboard'
get 'admin/text' => 'admin#text_dashboard'
get 'admin/blog' => 'admin#blog_dashboard'
get 'admin/', to: redirect('/admin/case')

get 'about' => 'pages#about'
get 'contact' => 'pages#contact'

resources :posts

resources :texts, only: [:update]

end

app/models/case.rb
class Case < ActiveRecord::Base
  acts_as_ordered_taggable_on :keywords
  validate :validate_keywords

  def keyword_string
    self.keyword_list.join(" – ")
  end

  def validate_keywords
    keyword_list.each do |keyword|
      keyword.sub!(/Keywords:\s*/i, "")
    end
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates_presence_of :body, :title
end

app/models/text.rb
class Text < ActiveRecord::Base
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  http_basic_authenticate_with CREDENTIALS

  def case_dashboard
    @cases = Case.all
  end

  def blog_dashboard
    @posts = Post.order(created_at: :desc)
  end

  def text_dashboard
    @texts = Text.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  CREDENTIALS = {name: Rails.application.secrets.admin_name,
                 password: Rails.application.secrets.admin_password}
end

app/controllers/cases_controller.rb
class CasesController < ApplicationController
  http_basic_authenticate_with CREDENTIALS.merge(only: [:create, :update, :destroy])

  before_action :retrieve_case, only: [:show, :edit, :update, :destroy]

  CASE_FIELDS = [:title, :summary, :keyword_list, :facts, :held, :comment]

  def index
    @cases = Case.all
    @cases_by_initial = @cases.group_by { |c| c.title[0].upcase }
  end

  def index_by_keyword
    @keywords = Case.tags_on(:keywords).map(&:name).sort
    @cases_by_keyword = Hash[@keywords.map do |keyword|
      [keyword, Case.tagged_with(keyword)]
    end]
    @keywords_by_initial = @keywords.group_by { |kw| kw[0].upcase }
  end

  def create
    @case = Case.new(params[:case].permit(CASE_FIELDS))
    if @case.save
      redirect_to @case, notice: 'Case successfully created.'
    else
      flash.now[:error] = 'Error: failed to save case'
      render :new
    end
  end

  def new
    @case = Case.new
  end

  def edit
  end

  def show
  end

  def update
    if @case.update(params[:case].permit(CASE_FIELDS))
      redirect_to @case, notice: 'Case successfully updated.'
    else
      flash[:error] = "Error: failed to save"
      render :edit
    end
  end

  def destroy
    @case.destroy
    flash[:notice] = "Case deleted"
    redirect_to admin_case_path
  end

  protected

  def retrieve_case
    @case = Case.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
    @about = Text.find_by_name('About').try(:text).try(:html_safe)
  end

  def contact
    @spencer_bio = Text.find_by_name('Spencer bio').try(:text).try(:html_safe)
    @monika_bio = Text.find_by_name('Monika bio').try(:text).try(:html_safe)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :retrieve_post, only: [:show, :edit, :update, :destroy]

  http_basic_authenticate_with CREDENTIALS.merge(only: [:create, :update, :destroy])

  def index
    @posts = Post.order(created_at: :desc)

    respond_to do |format|
      format.html
    end
  end

  def show
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post, notice: 'Post successfully created.'
    else
      render action: 'new' # errors auto-created by model validator failures
    end
  end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: 'Post was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @post.destroy
    redirect_to admin_blog_path
  end

  private
    def retrieve_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/controllers/texts_controller.rb
class TextsController < ApplicationController
  before_action :find_text, only: [:update]

  def update
    if @text.update(params[:text].permit(:text))
      redirect_to admin_text_path, notice: "#{@text.name} successfully updated"
    else
      flash[:error] = "Error: failed to save #{@text.name}"
      render 'admin#text_dashboard'
    end
  end

  private

  def find_text
    @text = Text.find_by_id(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def render_markdown(text)
    markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true)
    markdown.render(text.to_s).html_safe
  end
end

app/helpers/cases_helper.rb
module CasesHelper
end

app/helpers/navlink_helper.rb
module NavlinkHelper
  def link_unless_current(name, path)
    if current_page? path
      "<strong>#{name}</strong>".html_safe
    else
      link_to name, path
    end
  end
end

app/views/admin/_case.html.haml
%tr.caserow
  %td
    %p= link_to _case.title, case_path(_case)
  %td= link_to 'edit', edit_case_path(_case), class: 'intable button'
  %td= button_to 'delete', case_path(_case), method: :delete, data: {confirm: 'Are you sure you want to delete this case?'}, class: 'intable alert button'

app/views/admin/_nav.html.haml
%h1.adminheader
  = link_unless_current 'Blog dashboard', admin_blog_path
  &middot;
  = link_unless_current "Case dashboard", admin_case_path
  &middot;
  = link_unless_current "Text dashboard", admin_text_path

app/views/admin/_post.html.haml
%tr.caserow
  %td{width: '80%'}
    %p= link_to post.title, post_path(post)
  %td= link_to 'edit', edit_post_path(post), class: 'intable button'
  %td= button_to 'delete', post_path(post), method: :delete, data: {confirm: 'Are you sure you want to delete this post?'}, class: 'intable alert button'

app/views/admin/blog_dashboard.html.haml
= render 'nav'

= link_to 'New blog post', new_post_path, class: 'button success', id: 'newcasebutton'

%table{width: '100%'}
  %tbody
    = render partial: 'admin/post', collection: @posts

app/views/admin/case_dashboard.html.haml
= render 'nav'

= link_to 'Add a new case', new_case_path, class: 'button success', id: 'newcasebutton'

%table{width: '100%'}
  %tbody
    - cases_by_initial = @cases.group_by { |c| c.title[0] }
    - cases_by_initial.each_key.sort.each do |initial|
      %tr.initialrow
        %td
          %h3= initial
      = render partial: 'admin/case', collection: cases_by_initial[initial].sort_by(&:title), as: '_case'

app/views/admin/dashboard.html.haml
%h1 Admin dashboard

= link_to 'Add a new case', new_case_path, class: 'button success', id: 'newcasebutton'

%table{width: '100%'}
  %tbody
    - cases_by_initial = @cases.group_by { |c| c.title[0] }
    - cases_by_initial.each_key.sort.each do |initial|
      %tr.initialrow
        %td
          %h3= initial
      = render partial: 'case', collection: cases_by_initial[initial].sort_by(&:title), as: '_case'

app/views/admin/text_dashboard.html.haml
= render 'nav'

- @texts.each do |text|
  = form_for text do |f|
    = f.text_area :text, label: text.name, rows: 5
    = f.submit

app/views/cases/_case.html.haml
%tr.caserow
  %td
    %p= link_to _case.title, case_path(_case), class: 'casename'

app/views/cases/_form.html.haml
= form_for @case do |f|
  - if @case.errors.any?
    #error_explanation
      %h2= "#{pluralize(@case.errors.count, "error")} prohibited this case from being saved:"
      %ul
        - @case.errors.full_messages.each do |msg|
          %li= msg
  = f.text_field :title
  = f.text_field :keyword_list
  = f.text_area :summary, rows: 5
  = f.text_area :facts, rows: 10
  = f.text_area :held, rows: 10
  = f.text_area :comment, rows: 10
  = f.submit 'Submit'

app/views/cases/edit.html.haml
%h1 Edit case

= render 'form'

= link_to 'Back', admin_case_path

app/views/cases/index.html.haml
%h1 Cases by name

%input{type:"text", placeholder: "Filter by case name", id:"namefilter"}

%div{"data-magellan-expedition" => "fixed"}
  %dl.sub-nav
    - @cases_by_initial.each_key.sort.each do |initial|
      %dd{"data-magellan-arrival" => initial}
        %a{href: "##{initial}"}= initial

%table{width: '100%'}
  %tbody
    - @cases_by_initial.each_key.sort.each do |initial|
      %tr.initialrow
        %td
          %a{name: initial}
          %h3{"data-magellan-destination" => initial}= initial
      = render partial: 'case', collection: @cases_by_initial[initial].sort_by(&:title), as: '_case'

app/views/cases/index_by_keyword.html.haml
%h1 Cases by subject

%input{type:"text", placeholder: "Filter by subject", id:"kwfilter"}

%div{"data-magellan-expedition" => "fixed"}
  %dl.sub-nav
    - @keywords_by_initial.each_key.sort.each do |initial|
      %dd{"data-magellan-arrival" => initial}
        %a{href: "##{initial}"}= initial

%table{width: '100%'}
  %tbody
    - @keywords_by_initial.each_key.sort.each do |initial|
      %tr.initialrow
        %td
          %a{name: initial, "data-magellan-destination" => initial}
      - @keywords_by_initial[initial].each do |keyword|
        %tr.keywordrow
          %td
            %h3.keyword= keyword
            %table{width: '100%'}
              %tbody
                = render partial: 'case', collection: @cases_by_keyword[keyword].sort_by(&:title), as: '_case'

app/views/cases/new.html.haml
%h1 Add a new case

= render 'form'

= link_to 'Back', admin_case_path

app/views/cases/show.html.haml
.row
  .medium-10.columns.medium-centered

    %h2= @case.title

    %p.keywords= "Subjects: " + @case.keyword_string

    = render_markdown(@case.summary)

    %h3 Facts
    = render_markdown(@case.facts)

    %h3 Held
    = render_markdown(@case.held)

    %h3 Comment
    = render_markdown(@case.comment)

app/views/layouts/_footer.html.haml
.row
  .medium-12-columns#webdesign
    Web development by
    =link_to "Simon Woolf", "http://simonwoolf.net/"

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Zurb Foundation
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert-box round #{name.to_s == 'notice' ? 'success' : 'alert'}", "data-alert" => ""}
      = content_tag :div, msg
      %a.close{:href => "#"} &times;

app/views/layouts/_navigation.html.haml
-# navigation styled for Zurb Foundation 5
-# the syntax for data-topbar may need to change for Zurb Foundation 5
%nav.top-bar{"data-topbar" => true}
  %ul.title-area
    %li.name
      = link_to 'Disability Discrimination Update', root_path, id: 'title', class: 'hide-for-small-only'
      = link_to 'Disability Update', root_path, id: 'title', class: 'show-for-small-only'
    %li.toggle-topbar.menu-icon
      %a{:href => "#"}
        Menu
  %section.top-bar-section
    %ul.right
      = render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.haml
%li= link_to 'Home', about_path
%li= link_to 'Contact', contact_path
%li= link_to 'Blog', posts_path
%li.has-dropdown 
  = link_to 'Cases', '#'
  %ul.dropdown
    %li= link_to 'by name', cases_path
    %li= link_to 'by subject', by_keyword_cases_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Disability Discrimination'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Disability Discrimination'}"}
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    -# Modernizr is required for Zurb Foundation
    = javascript_include_tag "vendor/modernizr"
    = javascript_include_tag "application"
    /[if (lt IE 9) & (!IEMobile)]
      = stylesheet_link_tag "ie8.css?body=1"
      -# need html5shiv to make eg google webfonts work in IE8
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7/html5shiv.min.js"
    = csrf_meta_tags
    = favicon_link_tag "favicon.ico"
  %body
    #wrap
      %header
        = render 'layouts/navigation'
      .row#main-container
        %main{:role => "main"}
          = render 'layouts/messages'
          = yield
    #footer
      = render 'layouts/footer'
    /[if (lt IE 9) & (!IEMobile)]
      -# combination of this and the setting the grid width manually in ie8.css makes the grid work
      = javascript_include_tag "respond.min.js"

app/views/pages/about.html.haml
%h2#inpagetitle Disability Discrimination Update
%h4#byline From Spencer Keen and Monika Sobiecki


%p= @about

.row
  .small-6.medium-4.medium-offset-1.columns
    = link_to "Cases by name", cases_path, class: 'expand radius round button caseslink hide-for-small-only'
    = link_to "By name", cases_path, class: 'expand radius round button caseslink show-for-small-only'
  .small-6.medium-4.medium-offset-1.columns.end
    = link_to "Cases by subject", by_keyword_cases_path, class: 'expand radius round button caseslink hide-for-small-only'
    = link_to "By subject", by_keyword_cases_path, class: 'expand radius round button caseslink show-for-small-only'

.row
  .medium-5.medium-offset-3.columns
    = image_tag "disabilitysymbols.png", id: "symbols"

app/views/pages/contact.html.haml
.row
  .small-12.medium-5.medium-offset-1.columns
    = image_tag "spencer.jpg", class: 'portrait'
    %h4 Spencer Keen

    %p= @spencer_bio

    %hr

    %p.address Old Square Chambers
    %p.address 10-11 Bedford Row
    %p.address WC1R 4BU

    %hr

    %p.address 0117 930 5100
    %p.address= mail_to("keen@oldsquare.co.uk")
    = link_to image_tag("linkedin.png") + " LinkedIn", "https://www.linkedin.com/profile/view?id=51431139"

  .small-12.medium-5.medium-offset-1.columns.end
    = image_tag "monika.jpg", class: 'portrait'
    %h4 Monika Sobiecki

    %p= @monika_bio

    %hr

    %p.address Pump Court Chambers
    %p.address 3 Pump Court
    %p.address EC4Y 7AH

    %hr

    %p.address 0207 353 0711
    %p.address= mail_to("m.sobiecki@pumpcourtchambers.com")
    = link_to image_tag("linkedin.png") + " LinkedIn", "https://www.linkedin.com/profile/view?id=232329051"

app/views/posts/_form.html.haml
= form_for @post do |f|
  - if @post.errors.any?
    #error_explanation
      %h2= "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:"
      %ul
        - @post.errors.full_messages.each do |msg|
          %li= msg

  = f.text_field :title
  = f.text_area :body, rows: 15
  = f.submit 'Submit'

%p
  You can use 
  = link_to "markdown", "https://daringfireball.net/projects/markdown/basics"
  to format posts:

%table{width: '60%'}
  %tbody
    %tr
      %th{width: '50%', align: 'left'}
        Do this:
      %th{width: '50%', align: 'left'}
        to get this:
    %tr
      %td
        *Italics*
      %td
        %i italics
    %tr
      %td
        **Bold**
      %td
        %b Bold
    %tr
      %td
        [Google](http://google.co.uk)
      %td
        = link_to "Google", "http://google.co.uk"
    %tr
      %td
        &gt; Blockquote
      %td
        %blockquote Blockquote
    %tr
      %td
        \## Subheader
      %td
        %h2 Subheader
    %tr
      %td
        \### Subsubheader
      %td
        %h3 Subsubheader
    %tr
      %td
        \- Bulleted list
      %td
        %ul
          %li Bulleted list
    %tr
      %td
        Leave a blank line to get a line break.

app/views/posts/_post.html.haml
.blogpost
  %h1
    = link_to post.title, post_path(post)
    %small= post.created_at.to_s(format = :long)
  = render_markdown(post.body)

%hr

app/views/posts/edit.html.haml
%h1 Editing post

= render 'form'

= link_to 'Back', admin_blog_path

app/views/posts/index.html.haml
.row
  .medium-9.columns
    = render @posts
  .medium-3.columns.archive
    %h2 Archive
    - @posts.each do |post|
      %p= link_to post.title, post_path(post)

app/views/posts/new.html.haml
%h1 New post

= render 'form'

app/views/posts/show.html.haml
.row
  .medium-10.columns.medium-centered
    = render @post